title: Cyber blog
description: Here I write my random cyber notes, hope you can learn something from my scratches.
author: César Cruz
theme: minima

nav:
  - title: "Home"
    url: "/"
  - title: "About Me"
    url: "/aboutme/"
  - title: "Posts"
    url: "/posts/"
  - title: "Search"
    url: "/search/"
